### PR TITLE
MobileFirst Introduction

### PR DESCRIPTION
**Pull request by arpandesai**
Introduction of MobileFirst (iOS, macOS & Android Development Agency)

### CODE REVIEW

**Comment by arpandesai** [comment]
Hello, @brajeshwar - Feel free to modify 👍

**Comment by brajeshwar** [comment]
Good from my side.

**Comment by brajeshwar** [comment]
@arpandesai Can you please add the logo?

**Comment by arpandesai** [comment]
Added logo!

**Comment by saneef** [comment]
@arpandesai Do you guys have the logo in SVG? Or, add a 2x or 3x resolution PNGs

**Comment by arpandesai** [comment]
Can create 2x, 3x pngs. 

-- Arpan Desai 
+91 999 875-5114

**Comment by saneef** [comment]
@arpandesai Out of curiosity, the text on the Mobile First logo is not aligned exactly centre, it's slightly off to the right. Also, the baselines of the two words are out of aligned. Is that by design or some mistake?

**Comment by arpandesai** [comment]
It's certainly not by design. 

-- Arpan Desai 
+91 999 875-5114

**Comment by saneef** [comment]
No worries. I'll take care of it

**Comment by saneef** [comment]
@arpandesai Took liberty in make an SVG version of the logo https://github.com/alarisprime/alarisprime.com/blob/master/images/logo-mobilefirst.svg. Let me know if I need to fix something.

I'll push the updates in some time

**Comment by arpandesai** [comment]
Thank you for this love !!! 

— Arpan Desai

**Pull request merged**
