### PR TITLE
[WIP] Suggestions

### PR DESCRIPTION
**Pull request by prashaantt**
Here are some places that I found the website could be made clearer and a few minor issues fixed across a number of pages. These are only suggestive, please feel free to accept or reject as you please.

### CODE REVIEW

**Comment by brajeshwar** [comment]
This is cool. I think you're in the wrong field!
bicycle-parking-girl

**Comment by saneef** [comment]
Cool. @prashaantt tell me when you are ready to merge.

**Review by saneef — APPROVED** [review]

**Comment by prashaantt** [comment]
@brajeshwar I just like to be all over the place :)

@saneef Will be pushing more stuff over the next few days, will let you know when all done.

**Review by s3thi — APPROVED** [review]
Looks great. Merge.

**Comment by prashaantt** [comment]
Coming back to this after a long gap, I'm more wary of these changes to the projects page since they touch upon the amazing work of the awesome people at @alarisprime.

**Comment by prashaantt** [comment]
And the landing page, the hardest to get right! I have moved around things a bit, see if it works better for you guys. I find it helpful to build a local copy with these changes to compare with the live site.

I'm mostly done at this point, will probably need to review everything once more just to be sure.

**Review by brajeshwar — APPROVED** [review]
Good to go.

**Pull request merged**
